version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
#      - python/load-cache
#      - python/install-deps
#      - python/save-cache
      - run:
          name: Install code coverage deps
          command: |
            sudo apt update
            sudo apt install -y python3-coverage
            pip3 install coverage-badge
            python3-coverage erase

      - run:
          name: Test Unanimous keys
          command: ./tests/test-unanimous.sh

      - run:
          name: Test Threshold keys
          command: ./tests/test-threshold.sh

      - run:
          name: coverage test report
          command: |
            python3-coverage html --include=cosign
            coverage-badge > htmlcov/coverage.svg

      # Store the HTML coverage report
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
