version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
#      - python/load-cache
#      - python/install-deps
#      - python/save-cache
      - run:
          command: python3-coverage erase
          name: Initialize coverage test
      - run:
          command: ./tests/test-unanimous.sh
          name: Test Unanimous keys
      - run:
          command: ./tests/test-threshold.sh
          name: Test Threshold keys
      - run:
          command: python3-coverage html --include=cosign
          name: coverage test report
      - run:
          command: coverage-badge > htmlcov/coverage.svg
          name: coverage test badge

      # Store the HTML coverage report
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
